import Link from 'next/link';
import { notFound } from 'next/navigation';
import { PageShell } from '@/components/page-shell';
import { services } from '@/lib/services';
import { pageMetadata, jsonLd } from '@/lib/metadata';
type Props={params:Promise<{locale:string;slug:string}>};
export function generateStaticParams(){return Object.keys(services).map(slug=>({slug}));}
export async function generateMetadata({params}:Props){const {locale,slug}=await params;const service=services[slug as keyof typeof services];return service?pageMetadata(locale,`/services/${slug}`,service.title,service.summary):{};}
export default async function ServicePage({params}:Props){const {locale,slug}=await params;const service=services[slug as keyof typeof services];if(!service)notFound();return <PageShell locale={locale}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd({'@context':'https://schema.org','@type':'FAQPage',mainEntity:service.faq.map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))})}}/><p className="eyebrow">{service.eyebrow}</p><h1 className="page-title">{service.title}</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-slate-300">{service.summary}</p><Link className="meadow-button mt-8" href={`/${locale}/#contact`}>Discuss your project ↗</Link><div className="mt-16 max-w-3xl">{service.sections.map(([heading,text])=><section key={heading} className="content-section"><h2>{heading}</h2><p className="text-lg leading-8 text-slate-300">{text}</p></section>)}<section className="content-section"><h2>Frequently asked questions</h2>{service.faq.map(([q,a])=><details className="content-card" key={q}><summary className="cursor-pointer font-semibold text-white">{q}</summary><p className="mt-4">{a}</p></details>)}</section><div className="content-card mt-12"><h2 className="text-2xl font-semibold text-white">Let’s start with the problem.</h2><p className="my-4">Send a short brief, your existing setup and any constraints you already know.</p><Link className="meadow-button" href={`/${locale}/#contact`}>Get in touch →</Link><Link className="outline-button ml-3" href={`/${locale}/projects`}>See my work</Link></div></div></PageShell>;}
