import Link from 'next/link';
import { PageShell } from '@/components/page-shell';
import { resume } from '@/lib/resume';
import { pageMetadata } from '@/lib/metadata';
export async function generateMetadata({params}:{params:Promise<{locale:string}>}) {const {locale}=await params; return pageMetadata(locale,'/resume','Résumé — AI/ML & Python Backend',resume.summary);}
export default async function ResumePage({params}:{params:Promise<{locale:string}>}) {
 const {locale}=await params;
 return <PageShell locale={locale}><p className="eyebrow">Experience & education</p><h1 className="page-title">Prashant Choudhary</h1><p className="mt-4 text-xl text-violet-200">{resume.headline}</p><p className="mt-4 text-slate-400">{resume.location} · {resume.timezone}</p><div className="my-8 flex flex-wrap gap-3"><a className="meadow-button" href="/resume/Prashant_Choudhary_CV_EN.pdf" download>Download CV · English ↓</a><a className="outline-button" href="/resume/Prashant_Choudhary_CV_DE.pdf" download>Lebenslauf · Deutsch ↓</a></div><p className="max-w-3xl text-lg leading-8 text-slate-300">{resume.summary}</p><p className="mt-4 max-w-3xl text-slate-400">{resume.availability}</p><section className="content-section"><h2>Experience</h2>{resume.experience.map(e=><article className="content-card" key={e.title}><p className="eyebrow">{e.period}</p><h3>{e.title}</h3><p className="text-violet-200">{e.organization}</p><p className="mt-3">{e.detail}</p></article>)}</section><section className="content-section"><h2>Education</h2>{resume.education.map(e=><article className="content-card" key={e.title}><h3>{e.title}</h3><p>{e.organization} · {e.period}</p></article>)}</section><section className="content-section"><h2>Technical focus</h2><div className="flex flex-wrap gap-2">{resume.skills.map(s=><span className="tag" key={s}>{s}</span>)}</div></section><section className="content-section"><h2>Certifications</h2><ul className="list-disc space-y-3 pl-5">{resume.certifications.map(c=><li key={c}>{c}</li>)}</ul></section><section className="content-section"><h2>Languages</h2><ul className="space-y-2">{resume.languages.map(l=><li key={l}>{l}</li>)}</ul></section><Link className="outline-button mt-10" href={`/${locale}/projects`}>Explore selected projects →</Link></PageShell>;
}
