export const caseStudies = [
  {
    slug: 'pocketllm', title: 'PocketLLM ecosystem', category: 'LLM infrastructure',
    summary: 'Cloud-connected and local-first assistants built around a shared AI backend.',
    stack: ['Python', 'FastAPI', 'Flutter', 'Ollama', 'RAG', 'Supabase'], role: 'Builder and maintainer',
    challenge: 'Using language models across cloud providers and local hardware creates different requirements for credentials, model discovery, streaming and conversation storage. Users also need to understand where their data is processed.',
    approach: 'Separate provider integration from the client experience. Use a FastAPI backend for cloud-connected workflows and develop a local-first companion for offline inference and model management.',
    solution: 'The ecosystem includes provider abstraction, streaming inference, encrypted bring-your-own-key credentials and persistent conversations. PocketLLM Lite extends the local workflow with Ollama and GGUF model management, document ingestion, source-aware retrieval, tool calling, memories and Whisper transcription.',
    impact: 'The supplied CV reports 66+ GitHub stars and 11 forks for the main project. These are a dated CV snapshot, not live counters. The repository is the source for current release and adoption details.',
    metric: 'Cloud + local inference', repo: 'https://github.com/PocketLLM/PocketLLM',
  },
  {
    slug: 'setfit-reproduction', title: 'SetFit reproduction & paper-code audit', category: 'NLP research',
    summary: 'Reproducing few-shot classification and investigating a paper-to-code discrepancy.',
    stack: ['Python', 'PyTorch', 'Hugging Face', 'Sentence Transformers'], role: 'Independent implementation and evaluation',
    challenge: 'A reported machine-learning result is only useful when the experimental setup can be reproduced. Few-shot classification adds sensitivity to sampling and training configuration, so one successful run is insufficient evidence.',
    approach: 'Reimplement the SetFit workflow without the official SetFit package. Use deterministic sampling, contrastive sentence-encoder fine-tuning and downstream classification, then inspect the released source to compare implementation choices with the paper.',
    solution: 'The work combined a runnable training pipeline with repeated evaluation and controlled experiments. A discrepancy between the documented learning rate and the effective released implementation was investigated at source level and tested experimentally.',
    impact: 'The supplied CV reports 88.61 ± 1.61% accuracy across 10 independent CR MPNet runs, compared with the paper’s 88.5 ± 1.9%. The portfolio reproduces that CV claim; it does not present a new evaluation.',
    metric: '10 independent runs', repo: 'https://github.com/Mr-Dark-debug/setfit-reproduction',
  },
  {
    slug: 'aethermind-forge', title: 'AetherMind / Forge-1', category: 'Language model engineering',
    summary: 'A compact decoder-only language-model stack for constrained consumer GPUs.',
    stack: ['Python', 'PyTorch', 'Transformers', 'CUDA'], role: 'Architecture and training implementation',
    challenge: 'Training experiments on consumer hardware need explicit memory budgets. A model architecture that looks compact on paper can still exceed the available memory once activations, optimizer state and batches are included.',
    approach: 'Design a roughly 125-million-parameter variant targeting 4 GB VRAM and pair it with memory-aware training. Keep architecture, training, inference and evaluation in one inspectable implementation.',
    solution: 'The stack implements RMSNorm, Grouped Query Attention, RoPE, SwiGLU and weight tying. Training supports FP16 mixed precision, gradient checkpointing and gradient accumulation to work within constrained hardware.',
    impact: 'The CV documents the implemented architecture and the 4 GB VRAM design target. It does not provide a final benchmark or measured training throughput, so those outcomes are not claimed here.',
    metric: '~125M parameter variant', repo: 'https://github.com/Mr-Dark-debug/AetherMind',
  },
  {
    slug: 'moltjobs', title: 'Moltjobs', category: 'Applied AI product',
    summary: 'An AI-assisted job application workflow with reviewable changes and application tracking.',
    stack: ['LLM applications', 'Resume workflows', 'Product engineering'], role: 'Product builder',
    challenge: 'Job applications span several disconnected activities: maintaining a resume, adapting it to a role, tracking submissions and preparing for interviews. AI-written changes need to be inspectable before a candidate uses them.',
    approach: 'Connect those activities into one workflow and make tailored changes reviewable. Preserve the person’s ability to compare, revise and accept suggestions rather than treating generated text as a finished application.',
    solution: 'The platform includes resume creation and import, AI-assisted tailoring, reviewable diffs, application tracking, follow-ups, interview preparation and analytics-oriented workflows.',
    impact: 'The supplied CV reports more than 2,000 users. This is a self-reported CV metric rather than a live analytics count; no placement rate or hiring outcome is claimed.',
    metric: 'Reviewable AI tailoring', repo: null,
  },
] as const;
