import { PageShell } from '@/components/page-shell';
import { pageMetadata } from '@/lib/metadata';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  return pageMetadata(locale, '/privacy', 'Privacy', 'How this portfolio handles contact forms, AI questions, analytics and reading preferences.');
}

export default async function Privacy({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  return <PageShell locale={locale}><h1 className="page-title">Privacy</h1><div className="max-w-3xl"><section className="content-section"><h2>Contact and project enquiries</h2><p>Form submissions are sent to Formspree so Prashant can respond. Supply only the information needed for your enquiry. Do not include passwords or sensitive documents. Contact prashantc592114@gmail.com to ask about information you submitted.</p></section><section className="content-section"><h2>AI assistant</h2><p>Your question and recent conversation are sent to the configured AI provider to generate an answer. Public portfolio information may be included as context. The application does not intentionally store your conversation in its database. Avoid submitting confidential information. Hosting and model providers may retain operational logs under their own policies.</p></section><section className="content-section"><h2>Reading and subscriptions</h2><p>Bookmarks, reading progress, and external-media preferences stay in your browser. When persistent reactions are enabled, an anonymous reader cookie helps deduplicate reactions; it is not an account or cross-device identity. Email subscriptions require a confirmation link and can be removed through the unsubscribe link. The newsletter stores the email address and confirmation state.</p></section><section className="content-section"><h2>Analytics and external services</h2><p>Vercel Analytics and Speed Insights measure page use and performance. Events cover anonymous interactions such as project repository clicks, résumé downloads, article reads, and external-content choices without including form content. Error monitoring is enabled only when configured and excludes request content. GitHub comments and third-party embeds load only after you choose to open them. External links have their own privacy practices.</p></section><section className="content-section"><h2>Studio administration</h2><p>Studio is private, excluded from search engines, and protected by a short-lived HttpOnly session cookie. Password hashes, session secrets, GitHub tokens, AI keys, and analytics tokens remain server-side and are never sent to public visitors.</p></section></div></PageShell>;
}
